export const data = [
  {
      name: "TASK-2023-00001",
      subject: "Statutenwijziging doornemen / bespreken & ondertekenen",
      project: "PMVZW",
      type: null,
      status: "Completed",
      priority: "Medium",
      parent_task: null,
      department: null,
      color: "#29CD42",
      is_group: 0,
      exp_start_date: "2023-01-18",
      exp_end_date: "2023-01-26",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00002",
      subject: "Attachements <> Cherryfile integration",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "High",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00005",
      subject: "Preperations Serbian team",
      project: "ABPTech",
      type: null,
      status: "Completed",
      priority: "Urgent",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: "2023-01-26",
      exp_end_date: "2023-01-27",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00006",
      subject: "Opmaken volmacht voor 2023",
      project: "PMVZW",
      type: null,
      status: "Overdue",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: "2023-02-20",
      exp_end_date: "2023-02-24",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00007",
      subject: "Integration of user profile with Puxeo ERP",
      project: "SIO",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00008",
      subject: "Aanvraag erkenning bij de overheid",
      project: "PMVZW",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00009",
      subject: "Publicatie statutenwijziging live?",
      project: "PMVZW",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00010",
      subject: "Timesheets logs",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Medium",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00011",
      subject: "Setup DTAP environment",
      project: "Vaoix",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00013",
      subject: "Calender view",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Urgent",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00014",
      subject: "Dependenties over multiple projects",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Medium",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00015",
      subject: "Integration - Jira migration tool",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00016",
      subject: "Integration - Teams",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00017",
      subject: "Macro Planning",
      project: "CherryFile",
      type: null,
      status: "Completed",
      priority: "Low",
      parent_task: "TASK-2023-00020",
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00018",
      subject: "Sign in & Sign up",
      project: "UTIT",
      type: null,
      status: "Overdue",
      priority: "High",
      parent_task: "TASK-2023-00318",
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: "2023-02-05",
      exp_end_date: "2023-02-05",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00019",
      subject: "Puxeo ERP modulation",
      project: "PuxeoBacklog",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00020",
      subject: "PHASE0",
      project: "CherryFile",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 1,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00021",
      subject: "Fix cerfiticate issue",
      project: "CherryFile",
      type: null,
      status: "Overdue",
      priority: "Medium",
      parent_task: "TASK-2023-00020",
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: "2023-02-27",
      exp_end_date: "2023-02-27",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00022",
      subject: "Access team Serbia VM Cherryfile",
      project: "CherryFile",
      type: null,
      status: "Completed",
      priority: "Low",
      parent_task: "TASK-2023-00020",
      department: null,
      color: null,
      is_group: 0,
      exp_start_date: "2023-02-16",
      exp_end_date: "2023-02-16",
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  },
  {
      name: "TASK-2023-00023",
      subject: "PHASE1",
      project: "CherryFile",
      type: null,
      status: "Open",
      priority: "Low",
      parent_task: null,
      department: null,
      color: null,
      is_group: 1,
      exp_start_date: null,
      exp_end_date: null,
      expected_time: 0.0,
      total_costing_amount: 0.0,
      total_billing_amount: 0.0
  }
]
